### ISSUE TITLE
MongoS router Setup

### ISSUE THREAD

**Issue by mizhac** [Sirtea/www.linuxsysadmin.tk#1]
Hola, queria consultarte en el caso del MongoS (Router) cual era la configuracion respecto al articulo: https://github.com/Sirtea/www.linuxsysadmin.ml/blob/master/content/articles/mongodb-sharding-con-docker.md

> processManagement:
>   fork: false
> 
> net:
>   bindIp: 0.0.0.0
>   port: 27017
>   unixDomainSocket:
>     enabled: false
> 
> sharding:
>   configDb: config/config01:27019,config02:27019,config03:27019

En mi caso he configurado ello, pero queria saber cual era tu opinion. 
Gusto en revisar tu repositorio !

**Comment by Sirtea** [comment]
Hola,

He revisado el artículo y tienes razón... me comí la configuración del mongoS. He reproducido el artículo paso a paso y me ha quedado vacío.

Tras copiar una de las configuraciones de replica set, modificar el puerto (por comodidad), quitar el "storage" (que no se usa y evita que mongoS levante), el "replication" (tampoco se usa y también da problemas de ejecución), y añadir el "sharding.configDB" (necesario), el resultado es exactamente el que indicas.

He actualizado el repositorio añadiendo la configuración resultante (que es la misma exactamente que la tuya) y he regenerado el blog estático que se genera de este repositorio, que es https://www.linuxsysadmin.ml/

Un saludo

**Comment by mizhac** [comment]
Thanks a lot !
